# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

# HorizontalPodAutoscaler
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  cpuTargetAverageUtilization: 80
  memoryTargetAverageUtilization: 80

# Canary deployments
# If enabled, Istio v1.5+ and Flagger need to be installed in the cluster
canary:
  enabled: false
  progressDeadlineSeconds: 60
  canaryAnalysis:
    interval: "1m"
    threshold: 5
    maxWeight: 60
    stepWeight: 20
    # WARNING: Canary deployments will fail and rollback if there is no traffic that will generate the below specified metrics.
    metrics:
      requestSuccessRate:
        threshold: 99
        interval: "1m"
      requestDuration:
        threshold: 1000
        interval: "1m"
  # The host is using Istio Gateway and is currently not auto-generated
  # Please overwrite the `canary.host` in `values.yaml` in each environment repository (e.g., staging, production)
  host: acme.com

service:
  name: ota-update-frontend-viettel
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: |
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 400m
      nginx.org/client-max-body-size: 400m
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Access-Token, X-Auth-Request-User, X-Auth-Request-Email, X-Auth-Request-Preferred-Username, X-Auth-Request-Roles
      nginx.ingress.kubernetes.io/auth-signin: https://auth.jenkins-x-viettel.iviet.com/oauth2/start?rd=https%3A%2F%2F$http_host$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-url: https://auth.jenkins-x-viettel.iviet.com/oauth2/roles
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

backend:
  pr: # none
  prPrefix: jx-olli-ai-ota-update-v2-pr-
  namespace: # none
  name: ota-update-v2
  host: # none
  protocol: http

# custom ingress annotations on this service
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 400m
    nginx.org/client-max-body-size: 400m
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Access-Token, X-Auth-Request-User, X-Auth-Request-Email, X-Auth-Request-Preferred-Username, X-Auth-Request-Roles
    nginx.ingress.kubernetes.io/auth-signin: https://auth.jenkins-x-viettel.iviet.com/oauth2/start?rd=https%3A%2F%2F$http_host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.jenkins-x-viettel.iviet.com/oauth2/roles
